name: Dev CI - Integration Test

on:
  push:
    branches: [ dev ]

jobs:
  dev-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    # when use docker, it would be removed  
    - name: Install runtime deps
      run: |
        pip install -r requirements.txt
        pip install dvc dagshub mlflow


    - name: DVC pull
      run: dvc pull

    - name: Reproduce pipeline
      run: dvc repro

    - name: Push artifacts
      run: dvc push
